### ISSUE TITLE
[TensorRT] ERROR: Parameter check failed at: .........

### ISSUE THREAD

**Issue by wulixunhua** [mMikaa00/Yolov3-TensorRT-py#1]
When I load the onnx model and run yolo_test.py , rasie error: 

[TensorRT] ERROR: Parameter check failed at: ../builder/Network.cpp:: addInput:: 671, condition: isValidDims( dims, hasImplicitBatchDimension )

**Comment by mMikaa00** [comment]
You get your onnx model using model/convert_model.py?Can you paste your environment here.

**Comment by wulixunhua** [comment]
@mMikaa00  
The reason is that the model I used is not the same size as the input image in your yolo_test.py ?

my environment :
 Jetson agx  
ubuntu 1804
python3.6
tf=1.14 
tensorrt 6.0
cuda 10.0
cudnn 7.6.5
keras2onnx 1.6
onnx 1.6

**Comment by mMikaa00** [comment]
Your model has dynamic input shape, in convert_model.py, the model will be converted to static input shape. And tensorrt 6.0 may be not compatible with onnx 1.6. In my test, tensorrt6.0 didn't work well.

**Comment by wulixunhua** [comment]
@mMikaa00 I’ll try tensorrt7.0. Thank you very. ^_^

**Comment by wulixunhua** [comment]
@mMikaa00  Hi, Does your code only correspond to the 416_416 size image ? and the frozen .onnx model and the .h5 model should be 416_416 size ?

**Comment by mMikaa00** [comment]
If you want to adapt it to other size, just modify model_image_size in yolo_tensorrt.py.

**Comment by wulixunhua** [comment]
![6ba2157288aae42640c465dbcc2c7b5] (https://user-images.githubusercontent.com/32047846/77063684-11962280-6a19-11ea-9bfd-ea1ae817db30.jpg)

@mMikaa00  I upload the image. it's visual result of onnx model by running convert_model.py . This input is 1_0_0_3 .  Is that conversion wrong ? （Is the static input shape should be 1_416_416_3  ? ）

**Comment by mMikaa00** [comment]
Here is my onnx input info:
>>> model.graph.input[0]
name: "input_1"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 416
      }
      dim {
        dim_value: 416
      }
      dim {
        dim_value: 3
      }
    }
  }
}
You get your .h5 model from the link I recommended?

**Comment by wulixunhua** [comment]
![2de5234794f330637dc19dc746487d9](https://user-images.githubusercontent.com/32047846/77129574-83a94e80-6a8f-11ea-96b0-22b650e5ae9c.jpg)

@mMikaa00 Here is my .h5 model and I’ve tested it . 
I saw the convert_model.py didn't need input size( such as 416_416).  Is anything wrong with the .h5 model ?

**Comment by mMikaa00** [comment]
The convert_model.py means it won't change the input shape except the batch_size. It seems that your model has dynamic intput shape.
