### ISSUE TITLE
model how .onnx to .engine

### ISSUE THREAD

**Issue by woshizhangcheng** [mMikaa00/Yolov3-TensorRT-py#2]
hi:
   how to .onnx to .engine

**Comment by mMikaa00** [comment]
You can specify .onnx or .engine as model in yolo_test.py, if .onnx is specified, .engine will be generated automatically in the same directory.

**Comment by woshizhangcheng** [comment]
1. python model_data/convert_model.py --model_path=your_dir/yolo.h5 --output_path=./ --type=onnx
2.  python yolo_test.py --model ./converted.onnx --live --platform=tensorrt
parameter ： "infer_mode": "int8",
rasie error:
![Snipaste_2020-04-25_14-00-07](https://user-images.githubusercontent.com/34908468/80272540-3444e680-86fd-11ea-9fb3-7e6182a15deb.jpg)

**Comment by nobody-cheng** [comment]
![Snipaste_2020-04-25_14-00-07](https://user-images.githubusercontent.com/34908468/80272546-40c93f00-86fd-11ea-995c-d212e5504b8a.jpg)

**Comment by mMikaa00** [comment]
Please paste your environment first, I guess you are not using tensorrt7.0, or something wrong with the installation.
